FROM golang:1.10
RUN curl -L https://github.com/alecthomas/gometalinter/releases/download/v2.0.5/gometalinter-2.0.5-linux-amd64.tar.gz | tar -xz --strip-components=1 -C /bin
WORKDIR $GOPATH/src/github.com/andrewrynhard/fibonacci
COPY ./ ./
RUN chmod +x ./hack/test.sh
RUN ./hack/test.sh --lint
RUN ./hack/test.sh --unit
ARG TEST_HOST
ENV HOST $TEST_HOST
RUN ./hack/test.sh --integration
