FROM golang:1.10 AS build
RUN go get -u github.com/golang/dep/cmd/dep
WORKDIR $GOPATH/src/github.com/andrewrynhard/fibonacci
COPY ./ ./
RUN $GOPATH/bin/dep status
RUN CGO_ENABLED=0 go build -o /fib .

FROM scratch
COPY swagger /swagger
COPY --from=build /fib /fib
WORKDIR /
ENTRYPOINT ["/fib"]
