FROM golang:1.10 AS build
WORKDIR $GOPATH/src/github.com/andrewrynhard/fibonacci
COPY ./ ./
RUN CGO_ENABLED=0 go build -o /fib .

FROM scratch
COPY swagger /swagger
COPY --from=build /fib /fib
WORKDIR /
ENTRYPOINT ["/fib"]
